### PR TITLE
Remove explicit promise wrapping from controller

### PR DESCRIPTION
**Pull request by seregazhuk**
Currently, I'm playing around the demo and skeleton, trying to build something. I'm not sure if you did it on purpose to explicitly show that controllers return promises. But if under the hood the Kernel already does this job (wraps responses into promises) I think there is no need for this extra code. It makes the quick start even easier. 

What do you think?

### CODE REVIEW

**Comment by mmoreram** [comment]
Well, the controller do that wrapping, but if the domain work with a Promise, then the controller should return this promise.

The controller wraps as a Promise (In fact should wrap only if the response is not a promise) only to allow plain responses.

In this skeleton, and in particular this endpoint, I'd like to show that a Promise can be returned (is not functional, only informative).

Do you think we could do this in another way?

Thanks for the comment :D

**Comment by seregazhuk** [comment]
Yes, I understand your intention. From the other side, it confuses me when I delete the promise, and everything still works as expected. 

If you want to show the purpose of promises in the controller the following example will be more explicit:

```php
class DefaultController
{
    /**
     * @var LoopInterface
     */
    private $loop;

    public function __construct(LoopInterface $loop)
    {
        $this->loop = $loop;
    }

    /**
     * Default path.
     */
    public function __invoke(Request $request)
    {
        $deferred = new Deferred();
        $this->loop->addTimer(1, static function () use ($deferred) {
            $response = new JsonResponse(
                [
                    'message' => 'DriftPHP is working!',
                ], 200
            );
            $deferred->resolve($response);
        });

        return $deferred->promise();
    }

```

Maybe the skeleton should contain two controllers to explicitly show the difference. If you need to wait - use promises, if you are ready to go - return a response.

**Comment by seregazhuk** [comment]
~By the way, there is something wrong with the `watch` command. It seems like it doesn't rebuild the container (symfony). If I try to add a new dependency to the controller... yes, it triggers the restart, the controller requires a new argument, but the container doesn't know about it. And the app fails.~

My mistake, I didn't use `--debug` with watcher.

**Comment by seregazhuk** [comment]
Sorry,  maybe you are right with your approach 🙈 There more options you have (promise or plain response) to start the more complex it is.

**Pull request closed without merging**
